version: '3'
services:  
  16-customer-demo-app:
    image: florescua/16-customer-demo-app:0.1
    depends_on:
      mysqlc1:
        condition: service_healthy
    ports:
      - 8080:8080
  mysqlc1:
    image: mysql:8.0.27
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=web_customer_tracker 
      - MYSQL_USER=student 
      - MYSQL_PASSWORD=student
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s